language: node_js
node_js: node
after_success: coveralls < coverage/lcov.info
env:
  global:
  - COVERALLS_SERVICE_NAME=travis-pro
  - secure: F/S9AyIen6I3Lrti5UqSeTJZk9gMSSTNspPXbgGT04SKwdM/yC0O1+1yQKkgmWZXHW1R01gUT1qucy+OO7Os1CGoZJXQ2gluuAQ/kx74aC8uOOoUmIb0xqy96UDjgx2XLKzIBOA1uIj3Gs107XNpjtmXXTi02YfpzQIZ2GmKUKmm8ditPZnWJFk3XMtKlcxeHLhtWLRmXHEEg5FDK22djXcPJ4dHs5U1n3sgbekLunwlPzlSHPX+l4JIYAoo/9vBlVGQE69h1AHcYwGjqhUPa35FXBY2FWXElYj30gxf6sac3pCg0WlmrxSWqHG5ADr0S27RdL/4B1q97jvDvg3rOKYD2Q66SiJgVtuzLsouIIYf5e7qQIsaIkqg1k2pz+iz3zxtFNjF7xlF3RkDHc1KU9YhgwgnS5volypl1o+VDSNgL7uYimAXWcrsQbs4Q4rKdRh+kZuimBtx8WG6LBS/OPg07w9Sjr0tbdFerMX3yIyS4gAOFbFQBalrYRJK1aognLB72pLfC83v0a/DhSIqqoOYewCR336i74MTfC+1mOR8bvmHa3WU4d2uW4IyO+5qt3G41cVZMEMztVBBQUUATqiBnysLIee/i2xxM4Y87r4Y39gRSIdzXOe4oFBhuOvEVm7hMlH9vtM9BXzRdtWw3IKxZHEbEO0Z8CtnrZQGAQg=
